### ISSUE TITLE
SPARQL 1.1 support and status of the xsparql project

### ISSUE THREAD

**Issue by marco-brandizi** [semantalytics/xsparql#22]
I came up to this XSPARQL implementation while looking for a way to translate big RDF files to XML.

I've tried it a bit and I understand that it doesn't support SPARQL 1.1 (e.g., I got an error for a property path + [`ZeroOrMorePath`](https://www.w3.org/TR/sparql11-query/#propertypaths) clause: `...WHERE {$Person a/rdfs:subClassOf* foaf:Person; ...}`). I wonder if there are plans to update it and, in general, if the project is still maintained.

**Comment by zacharywhitley** [comment]
That's a good question. It's not being actively maintained. It's been forked from the main repo on SourceForge and had a couple of updates. I think I might have missed a commit or two that I should go back and grab. PR's are always welcome.

**Comment by zacharywhitley** [comment]
It's not being maintained. XSPARQL should support sparql 1.1 features. Please submit a bug report.
