### ISSUE TITLE
How to capture piece of XML to a literal as is?

### ISSUE THREAD

**Issue by VladimirAlexiev** [semantalytics/xsparql#38]
@nunolopes and @stefanbischof and @zacharywhitley  is it possible to use XSPARQL to capture XML in a literal as is?

I have an XML file with stuff like this:
```xml
      <plu:geometry>
        <gml:Polygon srsName="http://www.opengis.net/def/crs/EPSG/0/25833" srsDimension="2">
          <gml:exterior>
            <gml:LinearRing>
              <gml:posList>385919.31860777 5824690.697477636 ...</gml:posList>
            </gml:LinearRing>
          </gml:exterior>
        </gml:Polygon>
      </plu:geometry>
```
and I want to capture it as a GeoSPARQL literal like this:
```xquery
  <{$geo}> a geo:Geometry; geo:asGML {$parcel/plu:geometry}^^geo:gmlLiteral.
```

However it omits the XML elements and only captures the text content:
```ttl
<https://graphdb.accordproject.eu/resource/tegel/_bp_ueberbaubaregrundstuecksflaeche.49/geo> geo:asGML  """

              385640.0017969721 5824886.201519095 ...



      """^^geo:gmlLiteral .
```

I tried without `declare option saxon:output "method=text";` but it's even worse (the URLs are mangled):
```ttl
&lt;https://graphdb.accordproject.eu/resource/tegel/_bp_ueberbaubaregrundstuecksflaeche.48/geo&gt; geo:asGML  """



              385640.0017969721 5824886.201519095 ...



      """^^geo:gmlLiteral .
```

Asked on twitter: https://twitter.com/valexiev1/status/1744256929189318851

**Comment by VladimirAlexiev** [comment]
I tried to use https://www.w3.org/TR/xpath-functions-30/#func-serialize:
```
  <{$geo}> a geo:Geometry; geo:asGML {fn:serialize($parcel/plu:geometry)}^^geo:gmlLiteral.
```
but got this error from saxon:
```
Error on line 69 column 105
  XPST0017 XQuery static error near #...ze( $parcel/plu:geometry ), ""#:
    Unknown system function serialize()
```

Then I tried to use https://www.saxonica.com/html/documentation9.4/extensions/functions/serialize.html
or https://www.saxonica.com/html/documentation12/functions/saxon/serialize.html
(even though "The function is obsolescent; the standard fn:serialize() function in XPath 3.0 should be used in  reference.")
```sparql
  <{$geo}> a geo:Geometry; geo:asGML {saxon:serialize($parcel/plu:geometry,"xml")}^^geo:gmlLiteral.
```
but got
```
Error on line 69 of *module with no systemId*:
  XPST0017: Cannot find a matching 2-argument function named {http://saxon.sf.net/}serialize()
```

Saxon documentations says "Available since Saxon 7.1", and maybe I don't have that in my version of `xsparql`?
```
xsparql --version
XSPARQL CLI version 20140909
Copyright (C) 2014, NUI Galway, WU Wien, Politecnico di Milano, Vienna University of Technology
Written by Nuno Lopes, Stefan Bischof, Daniele Dell'Aglio and Axel Polleres
```
But https://xsparql.sourceforge.net/install.html talks of `saxon9`...

In https://github.com/semantalytics/xsparql/issues/2#issuecomment-460298785
@zacharywhitley commented "Feb 4, 2019: Updated to saxon 9.9.0-2".
Zachary, could you please put a jar of the latest version in `releases`?

Then I tried to convert to xquery and run it with saxon, and it gave a more specific error:
```
$ xsparql --rewrite-only -f xsparql.xquery xsparql.xsparql
$ xq xsparql.xquery input=...
Static error on line 68 at column 122 on line 1 of xsparql.xquery:
  XPST0017: Cannot find a matching 2-argument function named
  {http://saxon.sf.net/}serialize(). Saxon extension functions are not available under Saxon-HE
```

So I tried to go back to `fn:serialize()`. It passed that point but failed with another error:
```
xq xsparql-fn.xquery input=Tegel_12-62a_inspirePLU_25833.gml
Static error on line 78 at column 59 on line 1 of sparql-functions.xquery:
  XPST0017: Cannot find a matching 1-argument function named
  {http://xsparql.deri.org/demo/xquery/xsparql.xquery}_sparqlQuery()
```

**Comment by nunolopes** [comment]
I don't recall coming across a query that combines RDF with XML output (but it's been a long time).  All the examples I could find for geo data we were using just `lat` and `long` as triples. 

The closest query I could find is this: https://sourceforge.net/p/xsparql/code/HEAD/tree/trunk/release-notes.txt#l52 but it doesn't seem the github version has this latest version.

**Comment by VladimirAlexiev** [comment]
hi @nunolopes ! 
- The option `xsparql:keepRDFTerms "true"` allows me to preserve the structure of RDF terms, not the structure of XML fragments.
- I guess my version of `xsparql` embeds an old saxon that supports only XPath 2.0, where `fn:serialize` doesn't exist.
- But when I tried with external saxon (Saxon-HE 9.7.0.1J from Saxonica), I got this error. 
```
make xsparql-test.ttl
xsparql --rewrite-only xsparql.xsparql -f xsparql.xquery
xq.bat -q:xsparql.xquery input=inspire-plu/test.xml > xsparql-test.ttl
Static error on line 78 at column 59 on line 1 of sparql-functions.xquery:
  XPST0017: Cannot find a matching 1-argument function named
  {http://xsparql.deri.org/demo/xquery/xsparql.xquery}_sparqlQuery()
Static error(s) in query
```

@nunolopes why it cannot find `xsparql:_sparqlQuery()`?
The generated xquery starts like this:
```xq
import module namespace _xsparql = "http://xsparql.deri.org/demo/xquery/xsparql.xquery" 
                                at "jar:file:/C:/prog/xsparql/xsparql-cli-jar-with-dependencies.jar!/xquery/xsparql.xquery";
import module namespace xsparql = "http://xsparql.deri.org/demo/xquery/sparql-functions.xquery" 
                                at "jar:file:/C:/prog/xsparql/xsparql-cli-jar-with-dependencies.jar!/xquery/sparql-functions.xquery";
```

**Comment by VladimirAlexiev** [comment]
I looked inside `jar:file:/C:/prog/xsparql/xsparql-cli-jar-with-dependencies.jar!/xquery/xsparql.xquery` and figured out 
that there's a function `_xsparql:_serialize()` that does it.
However, I cannot invoke it as such since a prefix cannot start with `_` in the xsparql grammar.
So I just declared another prefix `xsparql2`:
```
prefix xsparql2: <http://xsparql.deri.org/demo/xquery/xsparql.xquery>
for $parcel in doc($input)/gml:FeatureCollection/gml:featureMember/plu:SupplementaryRegulation
let $url := local:base($parcel/@gml:id/string())
let $geo := fn:concat($url,"/geo")
construct {
  <{$url}> a cp:CadastralParcel; geo:hasDefaultGeometry <{$geo}>.
  <{$geo}> a geo:Geometry; geo:asGML {xsparql2:_serialize($parcel/plu:geometry)}^^geo:gmlLiteral.
}
```
